using ClaimAuto.HealthSystems.Server.Model;
using ClaimAuto.HealthSystems.Server.Services.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ClaimAuto.HealthSystems.Server.Services.Implementations
{
    public class AuditPackagePdfService : IAuditPackagePdfService
    {
        // ── IST timezone helper ───────────────────────────────────
        private static readonly TimeZoneInfo IST =
            TimeZoneInfo.FindSystemTimeZoneById(
                "India Standard Time");

        private static string ToIST(DateTime utc, string fmt) =>
            TimeZoneInfo.ConvertTimeFromUtc(utc, IST)
                .ToString(fmt);

        public byte[] GenerateAuditPackagePdf(
            AuditPackage package,
            AuditPackageData data)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var purple = "#667eea";
            var darkText = "#1e2a3a";
            var grayText = "#9e9e9e";
            var lightGray = "#e0e0e0";
            var lightBg = "#f5f5f5";
            var greenBg = "#dcfce7";
            var greenText = "#166534";
            var redBg = "#fee2e2";
            var redText = "#991b1b";

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x =>
                        x.FontSize(11)
                         .FontFamily("Helvetica")
                         .FontColor(darkText));

                    page.Content().Column(col =>
                    {
                        // ── HEADER ────────────────────────────────
                        col.Item().Row(row =>
                        {
                            row.RelativeItem().Row(r =>
                            {
                                r.ConstantItem(32).Height(32)
                                    .Background(purple)
                                    .AlignCenter().AlignMiddle()
                                    .Text("C")
                                    .FontSize(16).Bold()
                                    .FontColor("#ffffff");
                                r.ConstantItem(8);
                                r.RelativeItem().Column(inner =>
                                {
                                    inner.Item()
                                        .Text("ClaimAuto")
                                        .FontSize(16).Bold()
                                        .FontColor(purple);
                                    inner.Item()
                                        .Text("Health Insurance")
                                        .FontSize(9)
                                        .FontColor(grayText);
                                });
                            });

                            row.ConstantItem(150).Column(c =>
                            {
                                c.Item().AlignRight()
                                    .Text("Audit Package")
                                    .FontSize(9)
                                    .FontColor(grayText);
                                c.Item().AlignRight()
                                    .Text($"#PKG-{package.PackageID}")
                                    .FontSize(15).Bold()
                                    .FontColor(darkText);
                                c.Item().AlignRight()
                                    .Text(ToIST(package.GeneratedAt,
                                        "dd MMM yyyy"))
                                    .FontSize(9)
                                    .FontColor(grayText);
                            });
                        });

                        col.Item().Height(10);
                        col.Item().Height(2).Background(purple);
                        col.Item().Height(2);
                        col.Item().Height(0.5f).Background(lightGray);
                        col.Item().Height(14);

                        // ── TITLE ─────────────────────────────────
                        col.Item().AlignCenter()
                            .Text("Compliance Audit Package")
                            .FontSize(18).Bold()
                            .FontColor(darkText);
                        col.Item().Height(4);
                        col.Item().AlignCenter()
                            .Text($"Generated by {data.GeneratedByName} · " +
                                  $"{ToIST(package.GeneratedAt, "dd MMM yyyy, hh:mm tt")} IST")
                            .FontSize(9)
                            .FontColor(grayText);

                        col.Item().Height(20);

                        // ── Local helpers ─────────────────────────
                        void SectionTitle(string title)
                        {
                            col.Item()
                                .BorderBottom(1)
                                .BorderColor(lightGray)
                                .PaddingBottom(5)
                                .Text(title)
                                .FontSize(10).Bold()
                                .FontColor(purple);
                            col.Item().Height(8);
                        }

                        // ── Plain table — no color coding ─────────
                        void TwoColTable(
                            List<(string Label, string Value,
                                string? BgColor, string? ValColor)> rows)
                        {
                            col.Item().Table(table =>
                            {
                                table.ColumnsDefinition(c =>
                                {
                                    c.RelativeColumn(2.2f);
                                    c.RelativeColumn(1f);
                                });

                                foreach (var (label, value, _, _)
                                    in rows)
                                {
                                    table.Cell()
                                        .Background(lightBg)
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Padding(7)
                                        .Text(label)
                                        .FontSize(10)
                                        .FontColor(grayText);

                                    table.Cell()
                                        .Background("#ffffff")
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Padding(7)
                                        .Text(value)
                                        .FontSize(10).Bold()
                                        .FontColor(darkText);
                                }
                            });
                            col.Item().Height(16);
                        }

                        // ── SECTION 1 — Package Details ───────────
                        SectionTitle("Section 1 — Package Details");
                        TwoColTable(new()
                        {
                            ("Package ID",
                                $"#PKG-{package.PackageID}",
                                null, null),
                            ("Period Start",
                                ToIST(package.PeriodStart,
                                    "dd MMM yyyy"),
                                null, null),
                            ("Period End",
                                ToIST(package.PeriodEnd,
                                    "dd MMM yyyy"),
                                null, null),
                            ("Generated By",
                                data.GeneratedByName,
                                null, null),
                            ("Generated At",
                                ToIST(package.GeneratedAt,
                                    "dd MMM yyyy, hh:mm tt") + " IST",
                                null, null),
                            ("Organization",
                                data.OrganizationName,
                                null, null),
                        });

                        // ── SECTION 2 — Claims Summary ────────────
                        SectionTitle("Section 2 — Claims Summary");
                        TwoColTable(new()
                        {
                            ("Total Claims",
                                data.TotalClaims.ToString(),
                                null, null),
                            ("Submitted",
                                data.ClaimsSubmitted.ToString(),
                                null, null),
                            ("Under Review",
                                data.ClaimsUnderReview.ToString(),
                                null, null),
                            ("Validated",
                                data.ClaimsValidated.ToString(),
                                null, null),
                            ("Adjudicated",
                                data.ClaimsAdjudicated.ToString(),
                                null, null),
                            ("Approved",
                                data.ClaimsApproved.ToString(),
                                null, null),
                            ("Paid",
                                data.ClaimsPaid.ToString(),
                                null, null),
                            ("Rejected",
                                data.ClaimsRejected.ToString(),
                                null, null),
                        });

                        // ── SECTION 3 — Payments Summary ──────────
                        SectionTitle(
                            "Section 3 — Payments Summary");
                        TwoColTable(new()
                        {
                            ("Total Payments",
                                data.TotalPayments.ToString(),
                                null, null),
                            ("Executed",
                                data.ExecutedPayments.ToString(),
                                null, null),
                            ("Pending",
                                data.PendingPayments.ToString(),
                                null, null),
                            ("On Hold",
                                data.OnHoldPayments.ToString(),
                                null, null),
                            ("Total Amount Executed",
                                $"INR {data.TotalAmountPaid:N2}",
                                null, null),
                        });

                        // ── SECTION 4 — Adjudication Summary ──────
                        SectionTitle(
                            "Section 4 — Adjudication Summary");
                        TwoColTable(new()
                        {
                            ("Total Records",
                                data.TotalAdjudications.ToString(),
                                null, null),
                            ("Auto-Adjudicated",
                                data.AutoAdjudicated.ToString(),
                                null, null),
                            ("Manual Review",
                                data.ManualAdjudicated.ToString(),
                                null, null),
                            ("Approved",
                                data.AdjApproved.ToString(),
                                null, null),
                            ("Denied",
                                data.AdjDenied.ToString(),
                                null, null),
                            ("Denial Rate",
                                $"{data.DenialRate:F2}%",
                                null, null),
                        });

                        // ── SECTION 5 — Remittance Summary ────────
                        SectionTitle(
                            "Section 5 — Remittance Summary");
                        TwoColTable(new()
                        {
                            ("Total Generated",
                                data.TotalRemittances.ToString(),
                                null, null),
                            ("Sent",
                                data.RemittancesSent.ToString(),
                                null, null),
                            ("Acknowledged",
                                data.RemittancesAcknowledged
                                    .ToString(),
                                null, null),
                            ("Pending Acknowledgement",
                                data.RemittancesPending.ToString(),
                                null, null),
                        });

                        // ── SECTION 6 — Fraud Summary ─────────────
                        SectionTitle("Section 6 — Fraud Summary");
                        TwoColTable(new()
                        {
                            ("Total Claims Scored",
                                data.TotalScored.ToString(),
                                null, null),
                            ("High Risk (Score ≥ 70)",
                                data.HighRisk.ToString(),
                                null, null),
                            ("Cases Opened",
                                data.CasesOpened.ToString(),
                                null, null),
                            ("Cases Resolved",
                                data.CasesResolved.ToString(),
                                null, null),
                            ("Fraud Flag Rate",
                                $"{data.FraudRate:F2}%",
                                null, null),
                        });

                        // ── SECTION 7 — Audit Activity ────────────
                        SectionTitle(
                            "Section 7 — Audit Activity");
                        TwoColTable(new()
                        {
                            ("Total Audit Logs",
                                data.TotalLogs.ToString(),
                                null, null),
                            ("Payment Actions",
                                data.PaymentLogs.ToString(),
                                null, null),
                            ("Claim Actions",
                                data.ClaimLogs.ToString(),
                                null, null),
                            ("Remittance Actions",
                                data.RemittanceLogs.ToString(),
                                null, null),
                            ("Reconciliation Actions",
                                data.ReconciliationLogs.ToString(),
                                null, null),
                            ("Report Actions",
                                data.ReportLogs.ToString(),
                                null, null),
                            ("Other Actions",
                                data.OtherLogs.ToString(),
                                null, null),
                        });

                        // ── SECTION 8 — Reports Generated ─────────
                        SectionTitle(
                            "Section 8 — Reports Generated");

                        if (!data.Reports.Any())
                        {
                            col.Item()
                                .Background(lightBg)
                                .Padding(10)
                                .Text("No reports generated " +
                                      "in this period.")
                                .FontSize(10).Italic()
                                .FontColor(grayText);
                            col.Item().Height(16);
                        }
                        else
                        {
                            col.Item().Table(table =>
                            {
                                table.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(55);
                                    c.RelativeColumn(1.5f);
                                    c.RelativeColumn(2f);
                                    c.RelativeColumn(2f);
                                });

                                void HeaderCell(string text)
                                {
                                    table.Cell()
                                        .Background(lightBg)
                                        .BorderBottom(1)
                                        .BorderColor(lightGray)
                                        .Padding(6)
                                        .Text(text)
                                        .FontSize(9).Bold()
                                        .FontColor("#555555");
                                }

                                HeaderCell("ID");
                                HeaderCell("Scope");
                                HeaderCell("Generated At");
                                HeaderCell("Generated By");

                                foreach (var r in data.Reports)
                                {
                                    table.Cell()
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Padding(6)
                                        .Text($"#RPT-{r.ReportID}")
                                        .FontSize(9)
                                        .FontColor(darkText);

                                    table.Cell()
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Background("#f7f5ff")
                                        .Padding(6)
                                        .Text(r.Scope)
                                        .FontSize(9).Bold()
                                        .FontColor(purple);

                                    table.Cell()
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Padding(6)
                                        .Text(ToIST(r.GeneratedAt,
                                            "dd MMM yyyy"))
                                        .FontSize(9)
                                        .FontColor(darkText);

                                    table.Cell()
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Padding(6)
                                        .Text(r.GeneratedBy)
                                        .FontSize(9)
                                        .FontColor(darkText);
                                }
                            });
                            col.Item().Height(16);
                        }

                        // ── SECTION 9 — KPI Snapshot ──────────────
                        SectionTitle("Section 9 — KPI Snapshot");

                        if (!data.KPIs.Any())
                        {
                            col.Item()
                                .Background(lightBg)
                                .Padding(10)
                                .Text("No KPI data available.")
                                .FontSize(10).Italic()
                                .FontColor(grayText);
                            col.Item().Height(16);
                        }
                        else
                        {
                            col.Item().Table(table =>
                            {
                                table.ColumnsDefinition(c =>
                                {
                                    c.RelativeColumn(3f);
                                    c.RelativeColumn(1f);
                                    c.RelativeColumn(1f);
                                    c.RelativeColumn(1.3f);
                                });

                                void HeaderCell(string text)
                                {
                                    table.Cell()
                                        .Background(lightBg)
                                        .BorderBottom(1)
                                        .BorderColor(lightGray)
                                        .Padding(6)
                                        .Text(text)
                                        .FontSize(9).Bold()
                                        .FontColor("#555555");
                                }

                                HeaderCell("KPI");
                                HeaderCell("Target");
                                HeaderCell("Actual");
                                HeaderCell("Status");

                                foreach (var k in data.KPIs)
                                {
                                    table.Cell()
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Padding(6)
                                        .Text(k.Name)
                                        .FontSize(9)
                                        .FontColor(darkText);

                                    table.Cell()
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Padding(6)
                                        .Text(k.Target)
                                        .FontSize(9)
                                        .FontColor(grayText);

                                    table.Cell()
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Padding(6)
                                        .Text(k.CurrentValue)
                                        .FontSize(9).Bold()
                                        .FontColor(k.OnTarget
                                            ? greenText : redText);

                                    table.Cell()
                                        .Border(0.5f)
                                        .BorderColor(lightGray)
                                        .Background(k.OnTarget
                                            ? greenBg : redBg)
                                        .Padding(6)
                                        .Text(k.OnTarget
                                            ? "✓ On Target"
                                            : "✗ Below Target")
                                        .FontSize(9).Bold()
                                        .FontColor(k.OnTarget
                                            ? greenText : redText);
                                }
                            });
                            col.Item().Height(16);
                        }

                        col.Item().Height(20);

                        // ── FOOTER ────────────────────────────────
                        col.Item().Height(0.5f)
                            .Background(lightGray);
                        col.Item().Height(2);
                        col.Item().Height(2).Background(purple);
                        col.Item().Height(10);

                        col.Item().Row(row =>
                        {
                            row.RelativeItem().AlignMiddle()
                                .Column(c =>
                                {
                                    c.Item()
                                        .Text("System-generated document · " +
                                              "No signature required")
                                        .FontSize(9).Italic()
                                        .FontColor("#bbbbbb");
                                    c.Item().Height(2);
                                    c.Item()
                                        .Text($"DOC-PKG-{package.PackageID}" +
                                              $"-{ToIST(package.GeneratedAt, "yyyyMMdd")}")
                                        .FontSize(9)
                                        .FontColor("#bbbbbb");
                                });

                            row.ConstantItem(130).Column(c =>
                            {
                                c.Item().AlignRight().Row(r =>
                                {
                                    r.ConstantItem(18).Height(18)
                                        .Background(purple)
                                        .AlignCenter().AlignMiddle()
                                        .Text("C")
                                        .FontSize(9).Bold()
                                        .FontColor("#ffffff");
                                    r.ConstantItem(6);
                                    r.RelativeItem().AlignMiddle()
                                        .Text("ClaimAuto Health Insurance")
                                        .FontSize(10).Bold()
                                        .FontColor(purple);
                                });
                            });
                        });
                    });
                });
            }).GeneratePdf();
        }
    }
}