// <auto-generated />
using System;
using ClaimAuto.HealthSystems.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimAuto.HealthSystems.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527121153_AddClaimDocumentContent")]
    partial class AddClaimDocumentContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.AdjudicationRecord", b =>
                {
                    b.Property<int>("AdjID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdjID"));

                    b.Property<string>("AppliedRulesJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalculationsJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeductibleApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EngineVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int?>("PerformedByID")
                        .HasColumnType("int");

                    b.HasKey("AdjID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PerformedByID");

                    b.ToTable("AdjudicationRecords");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Appeal", b =>
                {
                    b.Property<int>("AppealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppealID"));

                    b.Property<byte[]>("AppealFilePDF")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecisionByID")
                        .HasColumnType("int");

                    b.Property<string>("DocumentsJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FiledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FiledBy")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppealID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("DecisionByID");

                    b.HasIndex("FiledBy");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.AuditLog", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetailsJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("ResourceID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AuditID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.AuditPackage", b =>
                {
                    b.Property<int>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageID"));

                    b.Property<string>("ContentsJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeneratedByID")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<byte[]>("PackageFilePDF")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.HasKey("PackageID");

                    b.HasIndex("GeneratedByID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("AuditPackages");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Claim", b =>
                {
                    b.Property<int>("ClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimID"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ExternalClaimRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalBilledAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("ClaimID");

                    b.HasIndex("ExternalClaimRef")
                        .IsUnique()
                        .HasFilter("[ExternalClaimRef] IS NOT NULL");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PolicyID");

                    b.HasIndex("MemberID", "PolicyID");

                    b.HasIndex("ProviderID", "ReceivedAt");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.ClaimDocument", b =>
                {
                    b.Property<int>("DocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocID"));

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileURI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OCRTextURI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("SHA256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<int?>("VerifiedByID")
                        .HasColumnType("int");

                    b.HasKey("DocID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("VerifiedByID");

                    b.ToTable("ClaimDocuments");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.ClaimDocumentContent", b =>
                {
                    b.Property<string>("FileGuid")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("FileBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FileGuid");

                    b.ToTable("ClaimDocumentContents");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.ClaimLine", b =>
                {
                    b.Property<int>("LineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineID"));

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosisCodesJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineBilledAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("LineStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("ProcedureCodesJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("LineID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("ClaimLines");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.ClaimTasks", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("ClaimTasks");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.EligibilityCheck", b =>
                {
                    b.Property<int>("CheckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckID"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int?>("PerformedByID")
                        .HasColumnType("int");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.Property<string>("ResultJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TTL")
                        .HasColumnType("int");

                    b.HasKey("CheckID");

                    b.HasIndex("MemberID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PerformedByID");

                    b.HasIndex("PolicyID");

                    b.ToTable("EligibilityChecks");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.FraudCase", b =>
                {
                    b.Property<int>("CaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseID"));

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceURIsJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestigationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpenedBy")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OpenedBy");

                    b.HasIndex("OrganizationID");

                    b.ToTable("FraudCases");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.FraudScore", b =>
                {
                    b.Property<int>("ScoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreID"));

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<string>("FactorsJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<decimal>("ScoreValue")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ScoringModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ScoreID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("FraudScores");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.KPI", b =>
                {
                    b.Property<int>("KPIID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KPIID"));

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("ReportingPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Target")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("KPIID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("KPIs");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("ContactInfoJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CoverageEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CoverageStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("PolicyID")
                        .HasColumnType("int");

                    b.Property<int?>("PolicyholderUserID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.HasIndex("MemberNumber")
                        .IsUnique()
                        .HasFilter("[MemberNumber] IS NOT NULL");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PolicyID");

                    b.HasIndex("PolicyholderUserID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClaimID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationID"));

                    b.Property<string>("BrandColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrganizationID");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("PayeeID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PayeeID");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Policy", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyID"));

                    b.Property<string>("CoverageRulesJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DeductibleAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NotifiedAt2Hours")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NotifiedAt7Days")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<decimal?>("OutOfPocketMax")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SumInsured")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("PolicyID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PlanCode")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Reconciliation", b =>
                {
                    b.Property<int>("ReconID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReconID"));

                    b.Property<string>("DiscrepanciesJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentsSummaryJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ReconFilePDF")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ReconciledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReconID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PerformedByID");

                    b.ToTable("Reconciliations");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Remittance", b =>
                {
                    b.Property<int>("RemittanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemittanceID"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RemitFilePDF")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("SentToProviderAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RemittanceID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PaymentID")
                        .IsUnique();

                    b.ToTable("Remittances");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<string>("MetricsJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("ParametersJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ReportFilePDF")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportID");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Rule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<string>("ActionExpressionJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionExpressionJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("RuleID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Subrogation", b =>
                {
                    b.Property<int>("SubroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubroID"));

                    b.Property<int>("ClaimID")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<decimal?>("RecoverableAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RecoveryAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPartyDetailsJSON")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubroID");

                    b.HasIndex("ClaimID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Subrogations");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsInNetwork")
                        .HasColumnType("bit");

                    b.Property<int>("LoginFailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LoginLockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MFACodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MFAEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MFAFailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("MFASecretKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.AdjudicationRecord", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("AdjudicationRecords")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("Organization");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Appeal", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("Appeals")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "DecisionBy")
                        .WithMany()
                        .HasForeignKey("DecisionByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "FiledByUser")
                        .WithMany()
                        .HasForeignKey("FiledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("DecisionBy");

                    b.Navigation("FiledByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.AuditLog", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.AuditPackage", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Claim", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Member", "Member")
                        .WithMany("Claims")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Organization");

                    b.Navigation("Policy");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.ClaimDocument", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("ClaimDocuments")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("Organization");

                    b.Navigation("Uploader");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.ClaimLine", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("ClaimLines")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.ClaimTasks", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("Tasks")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Claim");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.EligibilityCheck", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Member", "Member")
                        .WithMany("EligibilityChecks")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Policy", "Policy")
                        .WithMany("EligibilityChecks")
                        .HasForeignKey("PolicyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Organization");

                    b.Navigation("PerformedBy");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.FraudCase", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("FraudCases")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("OpenedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.FraudScore", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("FraudScores")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.KPI", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Member", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Policy", "Policy")
                        .WithMany("Members")
                        .HasForeignKey("PolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "PolicyholderUser")
                        .WithMany()
                        .HasForeignKey("PolicyholderUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");

                    b.Navigation("Policy");

                    b.Navigation("PolicyholderUser");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Notification", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("Notifications")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.PasswordResetToken", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Payment", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany("Payments")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Organization");

                    b.Navigation("Payee");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Policy", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Reconciliation", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedByID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Remittance", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Payment", "Payment")
                        .WithOne("Remittance")
                        .HasForeignKey("ClaimAuto.HealthSystems.Server.Model.Remittance", "PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Report", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Rule", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Subrogation", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.User", b =>
                {
                    b.HasOne("ClaimAuto.HealthSystems.Server.Model.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Claim", b =>
                {
                    b.Navigation("AdjudicationRecords");

                    b.Navigation("Appeals");

                    b.Navigation("ClaimDocuments");

                    b.Navigation("ClaimLines");

                    b.Navigation("FraudCases");

                    b.Navigation("FraudScores");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Member", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("EligibilityChecks");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Organization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Payment", b =>
                {
                    b.Navigation("Remittance");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.Policy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("EligibilityChecks");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ClaimAuto.HealthSystems.Server.Model.User", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
